image: 
  name: registry.gitlab.com/okrasolar/firmware/okra-edamame:0.0.5

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.only-default: &only-default
  - master
  - merge_requests
  - tags

test-native:
  stage: test
  only: *only-default
  script:
  - meson build 
  - cd build
  - ninja lint
  - ninja test